# 4. Inference

In [1]:
import sys, os
sys.path.append("../../..")

import pathSetting
import pandas as pd

from Clust.clust.ML.common.common import p1_integratedDataSaving as p1
from Clust.clust.ML.common.common import p2_dataSelection as p2
from Clust.clust.ML.common.common import p4_testing as p4
from Clust.clust.ML.regression import test as p4R
from Clust.clust.ML.forecasting import p5_inference as p5
from Clust.clust.ML.regression import app

import torch
#import main_regression as mr
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"{device}" " is available.")

cpu is available.


## 4-1. (just for test) Data Preparation 

In [2]:
# 0. pick only one data
DataMeta = p1.readJsonData(pathSetting.DataMetaPath)
dataList =  list(DataMeta.keys())
# dataX

dataName_X = dataList[2]
dataSaveMode_X = DataMeta[dataName_X]["integrationInfo"]["DataSaveMode"]

# datay
dataName_y = dataList[3]
dataSaveMode_y = DataMeta[dataName_y]["integrationInfo"]["DataSaveMode"]
dataFolderName = "data_integrated_result"
current = os.getcwd()
dataFolderPath = os.path.join(current, dataFolderName)

window_num =144
data_X = p2.getSavedIntegratedData(dataSaveMode_X, dataName_X, dataFolderPath)[:window_num]

In [3]:
from Clust.clust.ingestion.mongo import mongoClient as mongo_client
from Clust.setting import influx_setting_KETI as ins

mongo_client = mongo_client.mongoClient(ins.CLUSTMetaInfo2)

db_name = 'model'
collection_name = 'meta'

all_model_meta = mongo_client.get_all_document(db_name, collection_name)

In [4]:
db_name = 'model'
collection_name = 'meta'
search = {'modelName': 'EnergyLSTMRegression'}
model_meta= mongo_client.get_document_by_json(db_name, collection_name, search)
model_meta = model_meta[1]

In [5]:
#2
# from Clust.clust.transformation.type.NPArrayToDF import trans3NPtoDF
# inputXDF, y = trans3NPtoDF(inputX, inputy,'2000-1-1')

In [6]:
# 4. Testing
df_result = app.get_inference_result(data_X, model_meta, window_num)

['RH_1', 'RH_2', 'RH_3', 'RH_4', 'RH_5', 'RH_6', 'RH_7', 'RH_8', 'RH_9', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'Press_mm_hg', 'RH_out', 'T_out', 'Tdewpoint', 'Visibility', 'Windspeed']
['value']
{'num_layers': 2, 'hidden_size': 64, 'dropout': 0.1, 'bidirectional': True, 'lr': 0.0001, 'device': 'cpu', 'n_epochs': 10, 'batch_size': 16, 'input_size': 24, 'seq_len': 144}
================= self x =============================
[[[0.36427851 0.36427851 0.36510412 ... 0.41464086 0.41298963 0.40941198]
  [0.66494443 0.6638721  0.65802301 ... 0.64047573 0.64252291 0.64447261]
  [0.4563016  0.45489952 0.46113102 ... 0.4450849  0.44851223 0.4450849 ]
  ...
  [0.48868778 0.47963801 0.47058824 ... 0.67420814 0.67571644 0.67722474]
  [0.609375   0.609375   0.609375   ... 0.609375   0.609375   0.609375  ]
  [0.30769231 0.29487179 0.28205128 ... 0.53846154 0.51282051 0.48717949]]]
================= self x =============================

Start testing data

~~~~~~~~~~~~~~~~~~~~~~~~
tensor

In [7]:
df_result

value
0  11.656283